spring:
  config:
    activate:
      on-profile: local-h2-datasource
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  config:
    activate:
      on-profile: local-mysql-datasource
  datasource:
    url: jdbc:mysql://localhost:3306/batch?useSSL=false&serverTimezone=Asia/Seoul
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
---
spring:
  config:
    activate:
      on-profile: dev-mysql-datasource
  datasource:
    url: # dev mysql url
    driverClassName: com.mysql.cj.jdbc.Driver
    username: # dev mysql username
    password: # dev mysql password
