spring:
  profiles:
    active: local-mysql
    group:
      local-h2:
        - local-h2-datasource
      local-mysql:
        - local-mysql-datasource
      dev-mysql:
        - dev-mysql-datasource
    include: datasource
  batch:
    job:
      name: MYBATIS_CHUNK_JOB